name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Install dos2unix
        run: sudo apt-get install dos2unix
        
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r25b
          local-cache: true
                
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
               
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Exclude META-INF files from APK
        run: echo "packagingOptions { exclude 'META-INF/DEPENDENCIES' exclude 'META-INF/LICENSE' exclude 'META-INF/LICENSE.txt' exclude 'META-INF/license.txt' exclude 'META-INF/NOTICE' exclude 'META-INF/NOTICE.txt' exclude 'META-INF/notice.txt' }" >> app/build.gradle
                    
      - name: Upload APK
      - uses: actions/upload-artifact@v2
        with:
          name: absensi_adminsekolah.apk
          path: app/build/outputs/apk/debug/absensi_adminsekolah_$(date +%d.%m.%Y).apk
